---
- name: Redis setup
  hosts: cache
  gather_facts: yes

  tasks:
    
    - name: Install Redis
      become: yes
      apt:
        name: redis-server
        state: latest
        update_cache: true

    - name: Ensure Redis started
      become: true
      service:
        name: redis-server
        state: started
        enabled: yes